name: portfolio_maker_app
description: A mobile application to create and showcase your professional portfolio.

publish_to: 'none'

uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  flutter_downloader: ^1.11.4
  share_plus: ^10.1.4
  permission_handler: ^10.0.0
  mockito: ^5.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.6.0'

flutter:
  assets:
    - assets/images/bg.jpg
    - assets/images/default_profile.png
  uses-material-design: true