name: portfolio_maker_app
description: A mobile application to create and showcase your professional portfolio.

# The following line prevents packages that depend on generative code to pick
# up regenerated code if that code is added as a dependency to another package that
# transitively depends on this package.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Use with the CupertinoIcons class on iOS, macOS, and watchOS.
# Use with the Icons class on Android and the web.
uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2  # For selecting an image from the device gallery
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.6.0'

flutter:
  assets:
    - assets/images/  # Path to your images directory

  # Additional configurations for Flutter (optional)
  # For example, you could add fonts or custom themes here.